// <auto-generated />
using System;
using ContestManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContestManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312163636_AddVipData")]
    partial class AddVipData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContestManager.Models.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contests");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            AccessLevel = "Normal",
                            EndTime = new DateTime(2026, 3, 13, 16, 36, 36, 31, DateTimeKind.Utc).AddTicks(9034),
                            Name = "Sample Math Contest",
                            StartTime = new DateTime(2026, 3, 12, 16, 36, 36, 31, DateTimeKind.Utc).AddTicks(9029)
                        },
                        new
                        {
                            Id = 102,
                            AccessLevel = "VIP",
                            EndTime = new DateTime(2026, 3, 13, 16, 36, 36, 31, DateTimeKind.Utc).AddTicks(9053),
                            Name = "Exclusive VIP Challenge",
                            StartTime = new DateTime(2026, 3, 12, 16, 36, 36, 31, DateTimeKind.Utc).AddTicks(9051)
                        });
                });

            modelBuilder.Entity("ContestManager.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "3"
                        },
                        new
                        {
                            Id = 2,
                            IsCorrect = false,
                            QuestionId = 1,
                            Text = "5"
                        },
                        new
                        {
                            Id = 3,
                            IsCorrect = true,
                            QuestionId = 1,
                            Text = "4"
                        },
                        new
                        {
                            Id = 4,
                            IsCorrect = false,
                            QuestionId = 2,
                            Text = "1"
                        },
                        new
                        {
                            Id = 7,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "2"
                        },
                        new
                        {
                            Id = 8,
                            IsCorrect = true,
                            QuestionId = 2,
                            Text = "4"
                        },
                        new
                        {
                            Id = 10,
                            IsCorrect = false,
                            QuestionId = 3,
                            Text = "False"
                        },
                        new
                        {
                            Id = 11,
                            IsCorrect = true,
                            QuestionId = 3,
                            Text = "True"
                        });
                });

            modelBuilder.Entity("ContestManager.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContestId = 101,
                            Text = "What is 2+2?",
                            Type = "Single"
                        },
                        new
                        {
                            Id = 2,
                            ContestId = 101,
                            Text = "Select all even numbers.",
                            Type = "Multi"
                        },
                        new
                        {
                            Id = 3,
                            ContestId = 101,
                            Text = "The sky is blue. (True/False)",
                            Type = "TrueFalse"
                        });
                });

            modelBuilder.Entity("ContestManager.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Role = "Normal",
                            Username = "TestUser"
                        },
                        new
                        {
                            Id = 2,
                            Role = "VIP",
                            Username = "VipUser"
                        });
                });

            modelBuilder.Entity("ContestManager.Models.UserContest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("UserId");

                    b.ToTable("UserContests");
                });

            modelBuilder.Entity("ContestManager.Models.Option", b =>
                {
                    b.HasOne("ContestManager.Models.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContestManager.Models.Question", b =>
                {
                    b.HasOne("ContestManager.Models.Contest", null)
                        .WithMany("Questions")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContestManager.Models.UserContest", b =>
                {
                    b.HasOne("ContestManager.Models.Contest", "Contest")
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ContestManager.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ContestManager.Models.Contest", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ContestManager.Models.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
